spring.application.name=fileloader
spring.datasource.url=jdbc:postgresql://root:hi53OsvUYlf3VQtO1kGY08XD2Y8WcfCE@dpg-d76bou3uibrs73bi6eq0-a.ohio-postgres.render.com/ussd_mlqa
spring.datasource.username=root
spring.datasource.password=hi53OsvUYlf3VQtO1kGY08XD2Y8WcfCE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
